### ISSUE TITLE
When I use the pretrained CP，I get this error

### ISSUE THREAD

**Issue by Bosen-Zhang** [thunlp/RE-Context-or-Names#1]
File "main.py", line 299, in <module>                                                                      
    model = REModel(args)                                                                                    
  File "/RE-Context-or-Names-master/finetune/supervisedRE/code/model.py", line 27, in __init__      
    self.bert.load_state_dict(ckpt["bert-base"])                                                             
  File "/home/share/Anaconda3/envs/pre/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, i$
 load_state_dict                                                                                             
    self.__class__.__name__, "\n\t".join(error_msgs)))                                                       
RuntimeError: Error(s) in loading state_dict for BertModel:                                                  
        Missing key(s) in state_dict: "embeddings.position_ids". 

So is the pretrained model is usable？or should I do some other things？
Thanks！

**Comment by h-peng17** [comment]
Thank you for finding the problem！It seems to be the transformers problem, see https://github.com/huggingface/transformers/issues/6882 . There exists a big change on Bert embedding format after version 3.0.2. I run my code on version <= 3.0.2 and save the ckpt, but transformers in utils is the lastest version(3.5.0), so the bug occurs. I have changed the version to 3.0.2 and I can run the code normally. Don't forget re-install transformers in utils.
