### ISSUE TITLE
Having trouble reproducing tacred results

### ISSUE THREAD

**Issue by wjczf123** [thunlp/RE-Context-or-Names#16]
Hi,
The results on TACRED dataset seem have problem. 

CP	tacred	Sun Aug 15 08:35:41 2021
@RESULT: Best Dev score is 0.866, Test score is 0.882
--------------------------------------------------------------

And the results about BERT is also higher.

I only modify run.sh.

ckpt="CP"
for seed in 42 43 44 45 46
do
	bash train.sh 1 $seed $ckpt 1 20
done

Is the problem on dataset?

**Comment by wjczf123** [comment]
It seems that the statistics of TACRED (i.e., the number of train/dev/test) are correct.

**Comment by h-peng17** [comment]
Is the `NA` relation's id 0? You can check in your rel2id.json

**Comment by wjczf123** [comment]
Thank you very much. The id of NA is not 0, which caused the error. 

There are no restrictions on id of other relations?

**Comment by wjczf123** [comment]
In addition, is there a standard or code for data division? 
I can use this to get train_0.1.txt on TACRED dataset.

**Comment by h-peng17** [comment]
Yes. You should just ensure that id of `NA` is 0.

**Comment by h-peng17** [comment]
You can use this function https://github.com/thunlp/RE-Context-or-Names/blob/1c0cff9bf3137862488ef2792e051c7db2a4fb8d/utils/utils.py#L172

**Comment by wjczf123** [comment]
OK. Thanks, hope you have a nice day!
