### ISSUE TITLE
Pretrain Settings

### ISSUE THREAD

**Issue by jzhang38** [thunlp/RE-Context-or-Names#18]
I notice that in your pretrain README, for pretraining with CP, the script is:

python -m torch.distributed.launch --nproc_per_node 4  main.py \
	--cuda 4,5,6,7 \
	--model MTB \
	--lr 3e-5 --batch_size_per_gpu 32 --max_epoch 20 \
	--gradient_accumulation_steps 16 \
	--max_length 64 \
	--save_step 500 \
	--alpha 0.3 \
	--temperature 0.05 \
	--train_sample \
	--save_dir ckpt_cp \

Is it a typo that you writes "--model MTB"? Should it be "--model CP" instead?

Thank you.

Best regards,
Peiyuann

**Comment by h-peng17** [comment]
Yes, that may be a typo. If you want to pre-train CP, you should set `--model` param to `CP`.
