### ISSUE TITLE
Unable to read from pre-train data json file

### ISSUE THREAD

**Issue by akshat57** [thunlp/RE-Context-or-Names#20]
I've downloaded the pre-train file twice so far. Whenever I try to read it, get this error:

json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 25283907 (char 25283906)

**Comment by h-peng17** [comment]
Which link (Google Drive or Tsinghua Cloud) did you use? You can try the other link.

**Comment by akshat57** [comment]
Sorry didnt see that. Yes Tsinghua works
