### ISSUE TITLE
How to use CP as a encoder like BERT?

### ISSUE THREAD

**Issue by Xilihutu9** [thunlp/RE-Context-or-Names#21]
I just want to use CP as a basis encoder like BERT, which I needn't to train it again, so is there a pre-trained model that I can use directly without pre-training myself. If yes, whether the file I download from google driver supported from pre-train directory can be used directly?

**Comment by h-peng17** [comment]
We provided the pre-trained CP model, see https://github.com/thunlp/RE-Context-or-Names/tree/master/pretrain. You can download it and use the model as a basis encoder like BERT.
