### ISSUE TITLE
About the program stuck during pre-training

### ISSUE THREAD

**Issue by arrowfeng** [thunlp/RE-Context-or-Names#4]
Thanks for your work.
I encountered a problem during pre-training, and it seemed that the program was stuck.
this is my log
![image](https://user-images.githubusercontent.com/20623365/102422914-c14cff00-4042-11eb-88e1-50064ef444e4.png)

and my environment is as follows：
![image](https://user-images.githubusercontent.com/20623365/102422986-f1949d80-4042-11eb-874a-2a2f6cf71f6e.png)

**Comment by h-peng17** [comment]
Can you try to kill all processes and re-start the program? The negative sample function is memory-consuming. So it will be time-consuming in initial step.

**Comment by h-peng17** [comment]
And I will change the negative sample code to be more efficient in the near future.

**Comment by arrowfeng** [comment]
thank you
