### ISSUE TITLE
请问提供的两个预训练模型支持中文吗？

### ISSUE THREAD

**Issue by Single430** [thunlp/RE-Context-or-Names#6]
RT，非常感谢。

**Comment by h-peng17** [comment]
你好，目前不支持中文。
我们的预训练语料是英文的，BERT初始化参数也是英文bert-base-uncased。
如果有中文远程监督语料，可以直接用我们的代码进行训练（记得把bert-base-uncased换成chinese）。

**Comment by Single430** [comment]
好吧，好的，感谢。
