### ISSUE TITLE
What is the meaning of Dev score?

### ISSUE THREAD

**Issue by Allen920** [thunlp/RE-Context-or-Names#8]
Hi, I run the run.sh in the path of finetune/supervisedRE/code.  And I noticed that the terminal output printed the dev score. May I ask that what is the meaning of Dev score? Thank you!

**Comment by Allen920** [comment]
而且在微调完成之后，我看到log中的re_log输出了5次@ RESULT，
![image](https://user-images.githubusercontent.com/44702863/105451970-7022d180-5cb8-11eb-8d39-ba95669c0415.png)
但是我在main.py中看到这个@ RESULT的输出应该是在训练完之后只输出一次吧，请问为什么re_log中会输出5次result呢？
![image](https://user-images.githubusercontent.com/44702863/105452173-d14aa500-5cb8-11eb-9ba8-208ee3f40637.png)

**Comment by Allen920** [comment]
@h-peng17 hi 同学～如果看到的话可以解答一下issue吗，谢谢啦

**Comment by h-peng17** [comment]
Dev Score是验证集上的结果（F1或者accuracy）。输出5个结果是因为run.sh用5个不同的种子跑了5次平行实验，所以会有5个结果。取中位数就是最后的结果。

**Comment by Allen920** [comment]
噢噢明白了，感谢🙏！
